### ISSUE TITLE
Add TCP client

### ISSUE THREAD

**Issue by khoi** [khoiracle/swift-statsd-client#14]
Let's add in a TCP client as well

**Comment by yurrw** [comment]
Hey @khoiln , how can I get started ?

**Comment by khoi** [comment]
hi @yurrr, I think it'd be probably similar to our existing TCP client.

**Comment by yurrw** [comment]
I'll take a look in the morning and I'll  give you a feedback

**Comment by yurrw** [comment]
Hi, @khoiln I think I can't get a shot on it. sorry. Hope you find someone.

**Comment by khoi** [comment]
no problem @yurrr, have  a good day :)

**Comment by khoi** [comment]
Implemented in https://github.com/khoiln/swift-statsd-client/pull/16
